repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
      -   id: check-byte-order-marker
      -   id: check-case-conflict
      -   id: check-json
      -   id: check-yaml
          args: ['--allow-multiple-documents']
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: mixed-line-ending

    - repo: 'https://github.com/psf/black-pre-commit-mirror'
      rev: 23.11.0
      hooks:
        - id: black

    - repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
        - id: flake8
          name: "Lint code (flake8)"
          additional_dependencies:
            - "flake8==5.0.4"
            - "flake8-eradicate==1.4.0"
            - "flake8-mutable==1.2.0"
            - "flake8-pie==0.16.0"
            - "flake8-quotes==3.3.1"
            - "flake8-string-format==0.3.0"
            - "pep8-naming==0.13.2"
          args:
            ["--config=.flake8"]
