version: "3.9"
services:
  web:
    build: .
    environment:
      PORT: 9000
    ports:
      - "9000:9000"

  cloud-tasks:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/test-project/locations/here/queues/test-queue"
    ports:
      - "${TASKS_PORT:-8123}:8123"

